# Generated by Django 3.2.9 on 2022-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ravshan', max_length=255)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='backend_images')),
            ],
        ),
    ]
