# Generated by Django 3.2.9 on 2022-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='img',
            field=models.ImageField(upload_to='backend_images/main_table'),
        ),
    ]
